name: easy-queue
channels:
  - defaults
  - pypi
  - conda-forge
dependencies:
  - python=3.7.6
  - pip=19.3.1
  - flask=1.1.1
  - pymongo=3.9.0
  - python-dateutil=2.8.1
  - setuptools=44.0.0
  - sqlite=3.30.1
  - werkzeug=0.16.0
  - pip:
    - easyqueue-core
    - flask-pymongo==2.3.0
    - flask-restplus==0.9.2
    - flask-sqlalchemy==2.1
    - pytz==2019.3
    - schema==0.7.1
    - sqlalchemy==1.3.13
    - gunicorn

